// <auto-generated />
using System;
using System.Net;
using FormsManagementApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormsManagementApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251011000000_AddExportOptimizationIndexes")]
    partial class AddExportOptimizationIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            // Model configuration would be here - keeping it minimal for index-only migration
            // The actual model configuration is maintained in ApplicationDbContext
#pragma warning restore 612, 618
        }
    }
}