// <auto-generated />
using System;
using System.Net;
using FormsManagementApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FormsManagementApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250918135424_FixUserPasswords")]
    partial class FixUserPasswords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FormsManagementApi.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000001"),
                            Action = "CREATE_FORM",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 3, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Details = "{\"action\":\"create\",\"form_name\":\"Employee Onboarding Form\",\"form_code\":\"EMP_ONBOARD\"}",
                            ResourceId = new Guid("60000000-0000-0000-0000-000000000001"),
                            ResourceType = "Form",
                            UserId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000002"),
                            Action = "CREATE_FORM",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 6, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Details = "{\"action\":\"create\",\"form_name\":\"IT Support Request\",\"form_code\":\"IT_SUPPORT\"}",
                            ResourceId = new Guid("60000000-0000-0000-0000-000000000002"),
                            ResourceType = "Form",
                            UserId = new Guid("50000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("a0000000-0000-0000-0000-000000000003"),
                            Action = "SUBMIT_FORM",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 15, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Details = "{\"action\":\"submit\",\"form_name\":\"Expense Report\",\"amount\":1250.50}",
                            ResourceId = new Guid("80000000-0000-0000-0000-000000000003"),
                            ResourceType = "FormSubmission",
                            UserId = new Guid("50000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("FormsManagementApi.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "HR",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Human Resources Department",
                            Name = "Human Resources",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "IT",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Information Technology Department",
                            Name = "Information Technology",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "FIN",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "Finance Department",
                            Name = "Finance",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FormsManagementApi.Models.Form", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("FormSchema")
                        .HasColumnType("jsonb");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Settings")
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            Code = "EMP_ONBOARD",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("50000000-0000-0000-0000-000000000001"),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Form for collecting new employee information",
                            FormSchema = "{\"type\":\"object\",\"properties\":{\"firstName\":{\"type\":\"string\",\"title\":\"First Name\"},\"lastName\":{\"type\":\"string\",\"title\":\"Last Name\"},\"email\":{\"type\":\"string\",\"format\":\"email\",\"title\":\"Email\"},\"position\":{\"type\":\"string\",\"title\":\"Position\"},\"startDate\":{\"type\":\"string\",\"format\":\"date\",\"title\":\"Start Date\"}},\"required\":[\"firstName\",\"lastName\",\"email\",\"position\",\"startDate\"]}",
                            Name = "Employee Onboarding Form",
                            Settings = "{\"allowMultipleSubmissions\":false,\"requireAuthentication\":true}",
                            Status = "Active",
                            Title = "New Employee Onboarding",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            Code = "IT_SUPPORT",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("50000000-0000-0000-0000-000000000002"),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Form for submitting IT support requests",
                            FormSchema = "{\"type\":\"object\",\"properties\":{\"requestType\":{\"type\":\"string\",\"enum\":[\"Hardware\",\"Software\",\"Network\",\"Other\"],\"title\":\"Request Type\"},\"priority\":{\"type\":\"string\",\"enum\":[\"Low\",\"Medium\",\"High\",\"Critical\"],\"title\":\"Priority\"},\"description\":{\"type\":\"string\",\"title\":\"Description\"},\"contactInfo\":{\"type\":\"string\",\"title\":\"Contact Information\"}},\"required\":[\"requestType\",\"priority\",\"description\",\"contactInfo\"]}",
                            Name = "IT Support Request",
                            Settings = "{\"allowMultipleSubmissions\":true,\"requireAuthentication\":true}",
                            Status = "Active",
                            Title = "IT Support Request Form",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            Code = "EXP_REPORT",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("50000000-0000-0000-0000-000000000003"),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Form for submitting monthly expense reports",
                            FormSchema = "{\"type\":\"object\",\"properties\":{\"month\":{\"type\":\"string\",\"title\":\"Month\"},\"totalAmount\":{\"type\":\"number\",\"title\":\"Total Amount\"},\"category\":{\"type\":\"string\",\"enum\":[\"Travel\",\"Meals\",\"Office Supplies\",\"Other\"],\"title\":\"Category\"},\"receipts\":{\"type\":\"string\",\"title\":\"Receipt Numbers\"},\"notes\":{\"type\":\"string\",\"title\":\"Additional Notes\"}},\"required\":[\"month\",\"totalAmount\",\"category\"]}",
                            Name = "Expense Report",
                            Settings = "{\"allowMultipleSubmissions\":true,\"requireAuthentication\":true}",
                            Status = "Active",
                            Title = "Monthly Expense Report",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });

            modelBuilder.Entity("FormsManagementApi.Models.FormPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("FormId", "UserId")
                        .IsUnique();

                    b.ToTable("FormPermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2025, 9, 18, 13, 54, 23, 905, DateTimeKind.Utc).AddTicks(8998),
                            FormId = new Guid("60000000-0000-0000-0000-000000000001"),
                            Permission = "admin",
                            UpdatedAt = new DateTime(2025, 9, 18, 13, 54, 23, 905, DateTimeKind.Utc).AddTicks(8999),
                            UserId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2025, 9, 18, 13, 54, 23, 905, DateTimeKind.Utc).AddTicks(9004),
                            FormId = new Guid("60000000-0000-0000-0000-000000000002"),
                            Permission = "admin",
                            UpdatedAt = new DateTime(2025, 9, 18, 13, 54, 23, 905, DateTimeKind.Utc).AddTicks(9004),
                            UserId = new Guid("50000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("b0000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTime(2025, 9, 18, 13, 54, 23, 905, DateTimeKind.Utc).AddTicks(9007),
                            FormId = new Guid("60000000-0000-0000-0000-000000000003"),
                            Permission = "admin",
                            UpdatedAt = new DateTime(2025, 9, 18, 13, 54, 23, 905, DateTimeKind.Utc).AddTicks(9007),
                            UserId = new Guid("50000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("FormsManagementApi.Models.FormSchemaVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<string>("SchemaData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FormId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("FormSchemaVersions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("50000000-0000-0000-0000-000000000001"),
                            FormId = new Guid("60000000-0000-0000-0000-000000000001"),
                            SchemaData = "{\"type\":\"object\",\"properties\":{\"firstName\":{\"type\":\"string\",\"title\":\"First Name\"},\"lastName\":{\"type\":\"string\",\"title\":\"Last Name\"},\"email\":{\"type\":\"string\",\"format\":\"email\",\"title\":\"Email\"},\"position\":{\"type\":\"string\",\"title\":\"Position\"},\"startDate\":{\"type\":\"string\",\"format\":\"date\",\"title\":\"Start Date\"}},\"required\":[\"firstName\",\"lastName\",\"email\",\"position\",\"startDate\"]}",
                            VersionNumber = 1
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("50000000-0000-0000-0000-000000000002"),
                            FormId = new Guid("60000000-0000-0000-0000-000000000002"),
                            SchemaData = "{\"type\":\"object\",\"properties\":{\"requestType\":{\"type\":\"string\",\"enum\":[\"Hardware\",\"Software\",\"Network\",\"Other\"],\"title\":\"Request Type\"},\"priority\":{\"type\":\"string\",\"enum\":[\"Low\",\"Medium\",\"High\",\"Critical\"],\"title\":\"Priority\"},\"description\":{\"type\":\"string\",\"title\":\"Description\"},\"contactInfo\":{\"type\":\"string\",\"title\":\"Contact Information\"}},\"required\":[\"requestType\",\"priority\",\"description\",\"contactInfo\"]}",
                            VersionNumber = 1
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            CreatedBy = new Guid("50000000-0000-0000-0000-000000000003"),
                            FormId = new Guid("60000000-0000-0000-0000-000000000003"),
                            SchemaData = "{\"type\":\"object\",\"properties\":{\"month\":{\"type\":\"string\",\"title\":\"Month\"},\"totalAmount\":{\"type\":\"number\",\"title\":\"Total Amount\"},\"category\":{\"type\":\"string\",\"enum\":[\"Travel\",\"Meals\",\"Office Supplies\",\"Other\"],\"title\":\"Category\"},\"receipts\":{\"type\":\"string\",\"title\":\"Receipt Numbers\"},\"notes\":{\"type\":\"string\",\"title\":\"Additional Notes\"}},\"required\":[\"month\",\"totalAmount\",\"category\"]}",
                            VersionNumber = 1
                        });
                });

            modelBuilder.Entity("FormsManagementApi.Models.FormSubmission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<int?>("FormVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ResponseData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("SubmitterEmail")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<IPAddress>("SubmitterIp")
                        .HasColumnType("inet");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("UserId");

                    b.ToTable("FormSubmissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            FormId = new Guid("60000000-0000-0000-0000-000000000001"),
                            FormVersion = 1,
                            ResponseData = "{\"firstName\":\"Alice\",\"lastName\":\"Wilson\",\"email\":\"alice.wilson@company.com\",\"position\":\"Software Developer\",\"startDate\":\"2024-01-15\"}",
                            SubmittedAt = new DateTimeOffset(new DateTime(2025, 9, 8, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            SubmitterEmail = "alice.wilson@company.com"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000002"),
                            FormId = new Guid("60000000-0000-0000-0000-000000000002"),
                            FormVersion = 1,
                            ResponseData = "{\"requestType\":\"Hardware\",\"priority\":\"High\",\"description\":\"Laptop screen is flickering\",\"contactInfo\":\"ext. 1234\"}",
                            SubmittedAt = new DateTimeOffset(new DateTime(2025, 9, 13, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            SubmitterEmail = "john.smith@company.com"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000003"),
                            FormId = new Guid("60000000-0000-0000-0000-000000000003"),
                            FormVersion = 1,
                            ResponseData = "{\"month\":\"December 2024\",\"totalAmount\":1250.50,\"category\":\"Travel\",\"receipts\":\"R001, R002, R003\",\"notes\":\"Business trip to client site\"}",
                            SubmittedAt = new DateTimeOffset(new DateTime(2025, 9, 15, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            SubmitterEmail = "mike.davis@company.com"
                        });
                });

            modelBuilder.Entity("FormsManagementApi.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Resource")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Action = "Create",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Permission to create new forms",
                            IsActive = true,
                            Name = "Create Forms",
                            Resource = "Forms"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Action = "Edit",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Permission to edit existing forms",
                            IsActive = true,
                            Name = "Edit Forms",
                            Resource = "Forms"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Action = "View",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Permission to view forms",
                            IsActive = true,
                            Name = "View Forms",
                            Resource = "Forms"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Action = "Delete",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "Permission to delete forms",
                            IsActive = true,
                            Name = "Delete Forms",
                            Resource = "Forms"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Action = "Manage",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Permission to manage users",
                            IsActive = true,
                            Name = "Manage Users",
                            Resource = "Users"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000006"),
                            Action = "View",
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Permission to view reports",
                            IsActive = true,
                            Name = "View Reports",
                            Resource = "Reports"
                        });
                });

            modelBuilder.Entity("FormsManagementApi.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "HR Administrator role",
                            DisplayName = "HR Administrator",
                            IsActive = true,
                            IsSystemRole = false,
                            Name = "HR Admin",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "IT Manager role",
                            DisplayName = "IT Manager",
                            IsActive = true,
                            IsSystemRole = false,
                            Name = "IT Manager",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Finance Employee role",
                            DisplayName = "Finance Employee",
                            IsActive = true,
                            IsSystemRole = false,
                            Name = "Finance Employee",
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FormsManagementApi.Models.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000001"),
                            RoleId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000002"),
                            RoleId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000003"),
                            RoleId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000005"),
                            RoleId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000006"),
                            RoleId = new Guid("30000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("FormsManagementApi.Models.SuperAdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Permissions")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("SuperAdminUsers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "superadmin@system.com",
                            IsActive = true,
                            Name = "Super Administrator",
                            PasswordHash = "$2a$11$F1Axz0E4.u7WXI.ajFkQs.Houj5eJZrQkPD0TMtQM2re6mladap8m"
                        });
                });

            modelBuilder.Entity("FormsManagementApi.Models.UsageMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Details")
                        .HasColumnType("jsonb");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<int?>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("UsageMetrics");

                    b.HasData(
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000001"),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Details = "{\"period\":\"monthly\",\"forms\":[\"EMP_ONBOARD\"]}",
                            MetricType = "FormSubmissions",
                            RecordedAt = new DateTimeOffset(new DateTime(2025, 9, 17, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = 25
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000002"),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Details = "{\"period\":\"monthly\",\"forms\":[\"IT_SUPPORT\"]}",
                            MetricType = "FormViews",
                            RecordedAt = new DateTimeOffset(new DateTime(2025, 9, 17, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = 150
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000003"),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Details = "{\"period\":\"monthly\",\"unique_users\":12}",
                            MetricType = "ActiveUsers",
                            RecordedAt = new DateTimeOffset(new DateTime(2025, 9, 17, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            Value = 12
                        });
                });

            modelBuilder.Entity("FormsManagementApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CustomPermissions")
                        .HasColumnType("jsonb");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Profile")
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Email = "john.smith@company.com",
                            IsActive = true,
                            Name = "John Smith",
                            PasswordHash = "$2a$11$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
                            RoleId = new Guid("30000000-0000-0000-0000-000000000001"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Email = "sarah.johnson@company.com",
                            IsActive = true,
                            Name = "Sarah Johnson",
                            PasswordHash = "$2a$11$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
                            RoleId = new Guid("30000000-0000-0000-0000-000000000002"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            CreatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0)),
                            DepartmentId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Email = "mike.davis@company.com",
                            IsActive = true,
                            Name = "Mike Davis",
                            PasswordHash = "$2a$11$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi",
                            RoleId = new Guid("30000000-0000-0000-0000-000000000003"),
                            UpdatedAt = new DateTimeOffset(new DateTime(2025, 9, 18, 13, 54, 23, 653, DateTimeKind.Unspecified).AddTicks(4502), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("FormsManagementApi.Models.UserPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Granted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId", "PermissionId")
                        .IsUnique();

                    b.ToTable("UserPermissions");
                });

            modelBuilder.Entity("FormsManagementApi.Models.Webhook", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string[]>("Events")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FormId1")
                        .HasColumnType("uuid");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RetryConfig")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FormId");

                    b.HasIndex("FormId1");

                    b.ToTable("Webhooks");
                });

            modelBuilder.Entity("FormsManagementApi.Models.WebhookDelivery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text");

                    b.Property<int?>("ResponseStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("WebhookId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WebhookId");

                    b.ToTable("WebhookDeliveries");
                });

            modelBuilder.Entity("FormsManagementApi.Models.WebhookEndpoint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("WebhookEndpoints");
                });

            modelBuilder.Entity("FormsManagementApi.Models.AuditLog", b =>
                {
                    b.HasOne("FormsManagementApi.Models.Department", "Department")
                        .WithMany("AuditLogs")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormsManagementApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormsManagementApi.Models.Form", b =>
                {
                    b.HasOne("FormsManagementApi.Models.User", "Creator")
                        .WithMany("CreatedForms")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FormsManagementApi.Models.Department", "Department")
                        .WithMany("Forms")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FormsManagementApi.Models.FormPermission", b =>
                {
                    b.HasOne("FormsManagementApi.Models.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormsManagementApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Form");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormsManagementApi.Models.FormSchemaVersion", b =>
                {
                    b.HasOne("FormsManagementApi.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FormsManagementApi.Models.Form", "Form")
                        .WithMany("FormSchemaVersions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Creator");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("FormsManagementApi.Models.FormSubmission", b =>
                {
                    b.HasOne("FormsManagementApi.Models.Form", "Form")
                        .WithMany("FormSubmissions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormsManagementApi.Models.User", null)
                        .WithMany("FormSubmissions")
                        .HasForeignKey("UserId");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("FormsManagementApi.Models.Permission", b =>
                {
                    b.HasOne("FormsManagementApi.Models.Department", "Department")
                        .WithMany("Permissions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FormsManagementApi.Models.Role", b =>
                {
                    b.HasOne("FormsManagementApi.Models.Department", "Department")
                        .WithMany("Roles")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FormsManagementApi.Models.RolePermission", b =>
                {
                    b.HasOne("FormsManagementApi.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormsManagementApi.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FormsManagementApi.Models.UsageMetric", b =>
                {
                    b.HasOne("FormsManagementApi.Models.Department", "Department")
                        .WithMany("UsageMetrics")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FormsManagementApi.Models.User", b =>
                {
                    b.HasOne("FormsManagementApi.Models.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormsManagementApi.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FormsManagementApi.Models.UserPermission", b =>
                {
                    b.HasOne("FormsManagementApi.Models.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormsManagementApi.Models.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FormsManagementApi.Models.Webhook", b =>
                {
                    b.HasOne("FormsManagementApi.Models.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("FormsManagementApi.Models.Form", "Form")
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FormsManagementApi.Models.Form", null)
                        .WithMany("Webhooks")
                        .HasForeignKey("FormId1");

                    b.Navigation("Creator");

                    b.Navigation("Form");
                });

            modelBuilder.Entity("FormsManagementApi.Models.WebhookDelivery", b =>
                {
                    b.HasOne("FormsManagementApi.Models.Webhook", "Webhook")
                        .WithMany("Deliveries")
                        .HasForeignKey("WebhookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Webhook");
                });

            modelBuilder.Entity("FormsManagementApi.Models.WebhookEndpoint", b =>
                {
                    b.HasOne("FormsManagementApi.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("FormsManagementApi.Models.Department", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Forms");

                    b.Navigation("Permissions");

                    b.Navigation("Roles");

                    b.Navigation("UsageMetrics");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FormsManagementApi.Models.Form", b =>
                {
                    b.Navigation("FormSchemaVersions");

                    b.Navigation("FormSubmissions");

                    b.Navigation("Webhooks");
                });

            modelBuilder.Entity("FormsManagementApi.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("FormsManagementApi.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("FormsManagementApi.Models.User", b =>
                {
                    b.Navigation("CreatedForms");

                    b.Navigation("FormSubmissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("FormsManagementApi.Models.Webhook", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
